const productsData = [
  {
    id: 1,
    name: 'Kit pieles secas',
    shortDescription: 'Kit para pieles secas',
    longDescription: 'El kit para pieles secas es una solución completa para hidratar y cuidar la piel seca. Formulado con ingredientes especiales para retener la humedad y restaurar la suavidad y elasticidad de la piel seca.',
    price: 5000,
    image: 'img/prod 1.png',
    size: 'grande',
    category: 'cremas',
  },
  {
    id: 2,
    name: 'Kit pieles grasas',
    shortDescription: 'Kit para pieles grasas',
    longDescription: 'El kit para pieles grasas es una solución efectiva para controlar la producción de sebo y mantener la piel mate y equilibrada. Formulado con ingredientes que regulan la producción de aceite y reducen el brillo no deseado.',
    price: 5500,
    image: 'img/prod 2.png',
    category: 'cremas',
  },
  {
    id: 3,
    name: 'Kit pieles mixtas',
    shortDescription: 'Kit para pieles mixtas',
    longDescription: 'El kit para pieles mixtas es una combinación perfecta de productos para equilibrar y cuidar la piel mixta. Con ingredientes que hidratan las áreas secas y controlan el exceso de grasa en las áreas grasas para una piel uniforme y radiante.',
    price: 5800,
    image: 'img/prod 3.png',
    category: 'cremas',
  },
  {
    id: 4,
    name: 'Sombras',
    shortDescription: 'Sombras para ojos',
    longDescription: 'Las sombras para ojos son perfectas para crear una variedad de looks de maquillaje. Con una gama de tonos vibrantes y mates, estas sombras ofrecen una pigmentación intensa y duradera para resaltar y definir los ojos.',
    price: 8000,
    image: 'img/maquillaje 1.jpg',
    size: 'grande',
    category: 'maquillajes',
  },
  {
    id: 5,
    name: 'Brochas',
    shortDescription: 'Set de brochas de maquillaje',
    longDescription: 'El set de brochas de maquillaje es esencial para aplicar maquillaje de manera precisa y uniforme. Con una variedad de formas y tamaños, estas brochas están diseñadas para facilitar la aplicación de productos en diferentes áreas del rostro.',
    price: 7500,
    image: 'img/maquillaje 2.jpg',
    category: 'maquillajes',
  },
  {
    id: 6,
    name: 'Rimel',
    shortDescription: 'Rímel para pestañas',
    longDescription: 'El rímel para pestañas es un imprescindible en cualquier kit de maquillaje. Con su fórmula de alta calidad, este rímel alarga, voluminiza y define las pestañas para una mirada impactante y seductora.',
    price: 6800,
    image: 'img/maquillaje 3.jpg',
    category: 'maquillajes',
  },
  {
    id: 7,
    name: 'Exfoliante Facial',
    shortDescription: 'Exfoliante para el rostro',
    longDescription: 'El exfoliante facial es ideal para eliminar las células muertas de la piel y revitalizar la tez. Con ingredientes naturales y granulados suaves, este exfoliante deja la piel suave, radiante y lista para absorber mejor los tratamientos posteriores.',
    price: 8900,
    image: 'img/exfoliante 1.jpg',
    category: 'exfoliantes',
  },
  {
    id: 8,
    name: 'Exfoliante Corporal',
    shortDescription: 'Exfoliante para el cuerpo',
    longDescription: 'El exfoliante corporal es perfecto para suavizar y refrescar la piel de todo el cuerpo. Con ingredientes nutritivos y exfoliantes suaves, este exfoliante elimina las impurezas y deja la piel suave, luminosa y renovada.',
    price: 6700,
    image: 'img/exfoliante 2.jpg',
    category: 'exfoliantes',
  }
];

export default productsData;
